<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-27T00:45:20 IST" name="Default suite" finished-at="2024-11-27T00:46:13 IST" duration-ms="53014">
    <groups>
    </groups>
    <test started-at="2024-11-27T00:45:20 IST" name="Default test" finished-at="2024-11-27T00:46:13 IST" duration-ms="53014">
      <class name="com.test.fitpeo.test_Cases">
        <test-method is-config="true" signature="startup()[pri:0, instance:com.test.fitpeo.test_Cases@74e52ef6]" started-at="2024-11-27T00:45:20 IST" name="startup" finished-at="2024-11-27T00:45:25 IST" duration-ms="5239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method signature="test()[pri:0, instance:com.test.fitpeo.test_Cases@74e52ef6]" started-at="2024-11-27T00:45:25 IST" name="test" finished-at="2024-11-27T00:46:12 IST" duration-ms="46110" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$110700] but found [$75600]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$110700] but found [$75600]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.test.fitpeo.test_Cases.validateTotalRecurringReimbursement(test_Cases.java:102)
at com.test.fitpeo.test_Cases.test(test_Cases.java:139)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.test.fitpeo.test_Cases@74e52ef6]" started-at="2024-11-27T00:46:12 IST" name="quit" finished-at="2024-11-27T00:46:13 IST" duration-ms="1533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.test.fitpeo.test_Cases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
